### ISSUE TITLE
ClientId prefix on Logger name

### ISSUE THREAD

**Issue by sgdowney** [NLog/NLog.WCF#11]
Target configuration:
```
    <target xsi:type="LogReceiverService" name="WebLog" 
            useBinaryEncoding="false" endpointAddress="http://blahblah.com/WebLogger/WebLogReceiver.svc"
            clientId="ConsoleLogApp" includeEventProperties="true">
      <parameter layout="${longdate}" name="time" type="System.DateTime"/>
      <parameter layout="${machinename}" name="computer" type="System.String"/>
      <parameter name="level" layout="${level}" type="System.String"/>
      <parameter name="logger" layout="${logger}" type="System.String"/>
      <parameter name="exceptiontype" layout="${exception:format=Type}" type="System.String"/>
      <parameter name="message" layout="${message}" type="System.String"/>
      <parameter name="exception" layout="${exception:innerFormat=ToString:maxInnerExceptionLevel=3:format=ToString}" type="System.String"/>
    </target>
```
I have 2 console apps, .Net Framework 4.8 and .Net 7.0.  Both use the same target config but with different clientId values.  Log entries for the .Net Framework app have the logger name prefixed with the clientId specified in the target.  Log entries for the .Net 7.0 app do not have the clientId prefix on the logger name.  Everything else is working fine.  
NLog: 5.2.8
NLog.Wcf: 5.2.1
.Net 7 app also has
NLog.Extensions.Logging: 5.3.8

The NLog internal logs did not indicate any issues on the console apps nor on the service.  I'm not sure what to look at next.

**Comment by snakefoot** [comment]
Not an expert on NLog.WCF, but it seems the `clientId="ConsoleLogApp"` is added to `LogEventInfo.Properties`-collection.

I'm guessing you have two 2 parts:
- The remote WCF-LogReceiverService-Target that sends the `NLogEvents` where it assigns the ClientId.
- The central WCF-BaseLogReceiverForwardingService that receives the `NLogEvents` and converts them to LogEventInfo for actual logging. Where `ClientId` is added to `LogEventInfo.Properties`.

You have presented the configuration of the remote WCF-LogReceiverService-Target where `ClientId` is assigned. But I'm guessing you also have an additional configuration that performs the actual logging ?

**Comment by sgdowney** [comment]
Here is the target definition for the service that receives the logs.

```
      <target xsi:type="Database" name="DbLog" connectionStringName="LogDbContext" commandType="StoredProcedure" commandText=BLAHBLAH.LogRecord">
        <parameter name="recordTime" layout="${event-properties:item=time}" dbType="DateTime" allowDbNull="false"/>
        <parameter name="computer" layout="${event-properties:item=computer}" dbType="String" allowDbNull="false"/>
        <parameter name="logLevel" layout="${event-properties:item=level}" dbType="String" allowDbNull="false"/>
        <parameter name="logger" layout="${event-properties:item=logger}" dbType="String" allowDbNull="false"/>
        <parameter name="exceptionType" layout="${event-properties:item=exceptiontype}" dbType="String" allowDbNull="true"/>
        <parameter name="message" layout="${event-properties:item=message}" dbType="String" allowDbNull="false"/>
        <parameter name="exceptionData" layout="${event-properties:item=exception}" dbType="String" allowDbNull="true"/>
      </target>
```
All the fields in the table get populated.  The only difference is that the .Net 7.0 console app does not have the ClientId prefixed on the logger name.

Here's the code of the service.

```
using System.Linq;

using NLog;
using NLog.LogReceiverService;
namespace WebLogReceiver
{
    public class WebLogService : ILogReceiverServer
    {

        public void ProcessLogMessages(NLogEvents events)
        {
            var logEvents = events.ToEventInfo("Client.");

            foreach (var (ev, logger) in from LogEventInfo ev in logEvents
                                         let logger = LogManager.GetLogger(ev.LoggerName)
                                         select (ev, logger))
            {
                logger.Log(ev);
            }
        }
    }
}
```

**Comment by snakefoot** [comment]
I cannot see where in the NLog.WCF-target where `LoggerName` is being prefixed by the `ClientId` (`LogEventInfo.Properties` = `"ClientName"`).

Maybe something inside your own class that inherits from `BaseLogReceiverForwardingService` ?

**Comment by sgdowney** [comment]
The code above is the only code I've written for the log receiver service.

Here's the full code for the .Net 7 console app:

```
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

using NLog;
using NLog.Extensions.Logging;

using System.Text;

var logger = LogManager.GetCurrentClassLogger();
try
{
    var config = new ConfigurationBuilder()
       .SetBasePath(System.IO.Directory.GetCurrentDirectory()) //From NuGet Package Microsoft.Extensions.Configuration.Json
       .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
       .Build();

    using var servicesProvider = new ServiceCollection()
        .AddLogging(loggingBuilder =>
        {
            // configure Logging with NLog
            loggingBuilder.ClearProviders();
            loggingBuilder.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Trace);
            loggingBuilder.AddNLog();
        }).BuildServiceProvider();

    logger.Info("This is an info message.");
    try
    {
        throw new ApplicationException("Kaboom!!!");
    }
    catch (Exception ex)
    {
        logger.Error(ex, "An error has occurred.");

    }

}
catch (Exception ex)
{
    // NLog: catch any exception and log it.
    logger.Error(ex, "Stopped program because of exception");
    throw;
}
finally
{
    // Ensure to flush and stop internal timers/threads before application-exit (Avoid segmentation fault on Linux)
    LogManager.Flush();
    LogManager.Shutdown();
}
```

This is the code for the .Net Framework console app.

```
using System;

using NLog;
namespace ConsoleTestApp
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Logger logger = LogManager.GetCurrentClassLogger();
            try
            {
                throw new ApplicationException("Kaboom!!!");
            }
            catch (Exception ex)
            {
                logger.Error(ex, "An error has occurred.");
                
            }
            logger.Log(LogLevel.Info, "This is a message");
            LogManager.Flush();
        }
    }
}
```

**Comment by snakefoot** [comment]
Your current code will append `"Client."` to the logger-name:
```
var logEvents = events.ToEventInfo("Client.");
```
Maybe change to this code:
```
var logEvents = events.ToEventInfo(events.ClientId);
```
Maybe try debugging your custom `WebLogService`-class, and inspect the NlogEvents-input.

**Comment by sgdowney** [comment]
I made the suggested change above.  In the Console apps I also updated the `clientId` to be "ConsoleTestApp." (added a period to the end of the name).
When debugging the service I see the following:
When running the .Net Framework app, the logger name in the debugger is `ConsoleTestApp.ConsoleTestApp.Program`.
In the log file the logger name recorded is `ConsoleTestApp.Program`.
When running the .Net 7 app, the logger name in the debugger is `ConsoleTestApp.Program`.
In the log file the logger name recorded is `Program`.

**Comment by sgdowney** [comment]
Reverting the Log Receiver code  back to the original:

```
var logEvents = events.ToEventInfo("Client.");
```

When debugging the service I see the following:
When running the .Net Framework app, the logger name in the debugger is `Client.ConsoleTestApp.Program`.
In the log file the logger name recorded is `ConsoleTestApp.Program`.
When running the .Net 7 app, the logger name in the debugger is `Client.Program`.
In the log file the logger name recorded is `Program`.

For some reason, the .Net 7 console app is not prefixing the clientId to the logger name when the log events are sent to the service.
Here are the projects.
[WebLogReceiver.zip](https://github.com/NLog/NLog.WCF/files/13982001/WebLogReceiver.zip)

**Comment by snakefoot** [comment]
The LogManager.GetCurrentClassLogger() call in NET7 probably pickup a different class-name and namespace, because you going new style.

If you want specific Logger-name. Then you get full control by using LogManager.GetLogger("MyNameSpace.MyProgram")


Sent from my Galaxy



-------- Original message --------
From: Stewart Downey ***@***.***>
Date: 18/01/2024 23:01 (GMT+01:00)
To: "NLog/NLog.WCF" ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Comment ***@***.***>
Subject: Re: [NLog/NLog.WCF] ClientId prefix on Logger name (Issue #11)


Reverting the Log Receiver code back to the original:

var logEvents = events.ToEventInfo("Client.");


When debugging the service I see the following:
When running the .Net Framework app, the logger name in the debugger is Client.ConsoleTestApp.Program.
In the log file the logger name recorded is ConsoleTestApp.Program.
When running the .Net 7 app, the logger name in the debugger is Client.Program.
In the log file the logger name recorded is Program.

For some reason, the .Net 7 console app is not prefixing the clientId to the logger name when the log events are sent to the service.
Here are the projects.
WebLogReceiver.zip<https://github.com/NLog/NLog.WCF/files/13982001/WebLogReceiver.zip>

**Comment by snakefoot** [comment]
Created https://github.com/NLog/NLog/pull/5463 to add fallback to Assembly-Name when method without namespace

**Comment by snakefoot** [comment]
[NLog v5.3.1](https://www.nuget.org/packages/NLog) has been released, that adds fallback to use Assembly-name as namespace, when class-type has empty namespace when using `LogManager.GetCurrentClassLogger()`.
