### ISSUE TITLE
ClientOnProcessLogMessagesCompleted is inaccessible

### ISSUE THREAD

**Issue by ittegrat** [NLog/NLog.WCF#4]
I would like to inherit from `LogReceiverWebServiceTarget` and override the [`CreateLogReceiver`](https://github.com/NLog/NLog.WCF/blob/8394006bf5399a812de3794435702513b671b00a/src/NLog.Wcf/Targets/LogReceiverWebServiceTarget.cs#L295) method just to provide my own binding configuration. Unfortunately, the [`ClientOnProcessLogMessagesCompleted`](https://github.com/NLog/NLog.WCF/blob/8394006bf5399a812de3794435702513b671b00a/src/NLog.Wcf/Targets/LogReceiverWebServiceTarget.cs#L325) method is private.
Should I copy the code in my implementation or that method could be made `protected` ?
Thank you.

**Comment by snakefoot** [comment]
Think the cleanest approach is that you copy the implementation of `ClientOnProcessLogMessagesCompleted` to your own code.

**Comment by snakefoot** [comment]
Pull-requests are also wellcome to make it possible to control binding-configuration with help from NLog Layout-options.

**Comment by snakefoot** [comment]
Closing issue as resolved, due to inactivity.
